-- Align product categories with each brand's official site (balmainhair.com,
-- maisoneloure.com, eaude1974.com), checked 2026-09-30. Existing products only.
-- Matched by brand + name (ids differ per environment) and only where the row
-- still has its original seeded category, so admin edits are never overwritten.

UPDATE "Product" SET "category" = '["Styling Tools","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = '14k Gold Plated Cutting Comb' AND "category" = 'Styling Tools';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = '5 Weeks Enriching Hair Treatment' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Acetate Headband Black/White' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Acetate Headband Tortoise' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Acetate Headband White/Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Styling Tools","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'All Purpose SPA Brush' AND "category" = 'Styling Tools';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Argan Moisturizing Elixir' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Gifts","Hair Care"]' WHERE "brand" = 'balmain' AND "name" = 'Balmain Homme Gift Set' AND "category" = 'Gifts';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet","New"]' WHERE "brand" = 'balmain' AND "name" = 'Barrette Pour Cheveux Medium Silver/Gold' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Barrette Pour Cheveux Medium Tortoiseshell' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Gifts","Hair Care"]' WHERE "brand" = 'balmain' AND "name" = 'Bodyfying Homme Set' AND "category" = 'Gifts';
UPDATE "Product" SET "category" = '["Gifts","Hair Care"]' WHERE "brand" = 'balmain' AND "name" = 'Cosmetic Bag Cosmic Sapphire' AND "category" = 'Gifts';
UPDATE "Product" SET "category" = '["Hair Care","New"]' WHERE "brand" = 'balmain' AND "name" = 'Couleurs Couture Mask' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Gold Plated Hair Slide Logo' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Hair Parfume Vetiver 15ml' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Homme Hair Parfume' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Accessories","Archives","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Leather Headband Large Silver' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Archives","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Acetate Headband Large FW24' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Headband FW22' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Midnight Black Barrette' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Midnight Black Clip' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Midnight Black Headband' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Midnight Black Slides Pins' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Archives","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Pearl Hair Clip Large FW24' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Pinces à Cheveux Extra Small Midnight Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Pinces à Cheveux Medium Midnight Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Pont des Arts Hair Clip Large FW22' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition Printemps Leaf Slide' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","Archives","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition White Leather Puffed Headband' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Styling Tools","New"]' WHERE "brand" = 'balmain' AND "name" = 'Limited Edition legacy Spa Brush' AND "category" = 'Styling Tools';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Moisturizing Care Set' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Moisturizing Conditioner' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Muse de Printemps Styling Set' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Overnight Repair Serum' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince a Cheveux Imperiale Black/White' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince a Cheveux Imperiale Tortoise' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince a Cheveux Imperiale White/Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince a Cheveux Large White Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince a Cheveux Medium White Black' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince à Cheveux Extra Small Black/White' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince à Cheveux Large Black/White' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Accessories","New"]' WHERE "brand" = 'balmain' AND "name" = 'Pince à Cheveux Medium Black/White' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Rafia Cosmetic Bag' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Revitalizing Care Set' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Accessories","Outlet"]' WHERE "brand" = 'balmain' AND "name" = 'Riviera Headband Cognac Large' AND "category" = 'Hair Accessories';
UPDATE "Product" SET "category" = '["Hair Care","New"]' WHERE "brand" = 'balmain' AND "name" = 'Sculpting Wax 100 ml' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Bestsellers"]' WHERE "brand" = 'balmain' AND "name" = 'Texturizing Volume Spray' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Toiletry Bag Black Gold' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Hair Care","Gifts"]' WHERE "brand" = 'balmain' AND "name" = 'Volume Set Versailles FW24' AND "category" = 'Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Define & Smooth Spray – EAU de Santorini 200ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hair Perfume 15ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hair Perfume 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hyaluronic Glow ​Body Lotion 200ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hyaluronic Plump Hydrating Shampoo 250ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hyaluronic Plump Hydrating Shampoo 750ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hyaluronic Renew Hydrating Mask 200ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hyaluronic Renew Hydrating Mask 750ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hydrate & Protect Hand Cream 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hydrate & Renew Giftset' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Hydrate & Shield Leave-in Conditioner 125ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Salt & Grip Volumizing Spray 200ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Beauty","Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Capri Scent & Smooth Giftset' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Hamptons Hair Perfume 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Hamptons Hyaluronic Glow Body Lotion 200ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Santorini Hair Perfume 15ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Santorini Hair Perfume 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Santorini Hair Perfume Giftset' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'EAU de Santorini Hyaluronic Glow Body Lotion 200ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Fiber & Style - EAU de Capri 100ml' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Beauty","Sensorial Hair Care"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Glow & Shimmer Hair and Body Spray' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Hyaluronic Body wash - EAU de Capri 250ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Hyaluronic Body wash - EAU de Hamptons 250ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Hyaluronic Body wash - EAU de Santorini 250ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Hydrate & Protect Hand Cream - EAU de Hamptons 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Beauty","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Hydrate & Protect Hand Cream - EAU de Santorini 50ml' AND "category" = 'Sensorial Beauty';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Lift & Texture Volumizing Spray 200ml - EAU de Hamptons' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Lift & Thicken Volumizing Lotion 150ml - EAU de Hamptons' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Lifestyle","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Room Spray - EAU de Capri 200ml' AND "category" = 'Sensorial Lifestyle';
UPDATE "Product" SET "category" = '["Sensorial Lifestyle","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Room Spray - EAU de Hamptons 200ml' AND "category" = 'Sensorial Lifestyle';
UPDATE "Product" SET "category" = '["Sensorial Lifestyle","EAU de Santorini"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Room Spray - EAU de Santorini 200ml' AND "category" = 'Sensorial Lifestyle';
UPDATE "Product" SET "category" = '["Sensorial Lifestyle","EAU de Capri"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Scented Candle - EAU de Capri 200gr' AND "category" = 'Sensorial Lifestyle';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Volume & Lift Conditioner 750ml - EAU de Hamptons' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Volume & Lift Shampoo 250ml - EAU de Hamptons' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Sensorial Hair Care","EAU de Hamptons"]' WHERE "brand" = 'eau-de-1974' AND "name" = 'Volume & Lift Shampoo 750ml - EAU de Hamptons' AND "category" = 'Sensorial Hair Care';
UPDATE "Product" SET "category" = '["Care Collection","Silver & Blonde","Color-Treated/Damaged Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Colour Protecting Conditioner - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Silver & Blonde","Color-Treated/Damaged Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Colour Protecting Mask - 190 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Silver & Blonde","Color-Treated/Damaged Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Colour Protecting Shampoo - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Curl Cream - 150 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Treatments & Sets","Care Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Discovery Set' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Styling Collection","Care Collection","Fine Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Dry Shampoo - 300 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Elora (Travel Size) - 15 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Elora - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Grace (Travel Size) - 15 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Grace - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Reflect (Travel Size) - 15 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Hair Perfume","Styling Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Hair Perfume Reflect - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Care Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Heat Protection Mist - 200 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Treatments & Sets","Care Collection","Color-Treated/Damaged Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Intense Bond-Repair Treatment - 3x20 ml' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Care Collection","Color-Treated/Damaged Hair","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Intense Repair Serum - 30 ml' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Styling Collection","Care Collection","Dry Hair","Fine Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Leave-in Conditioning Mist - 200 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Conditioner (Travel Size) - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Conditioner - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Mask (Travel Size) - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Mask - 190 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Shampoo (Travel Size) - 50 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Dry Hair","Curly Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Shampoo - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Dry Hair","Curly Hair","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Moisturizing Styling Cream - 150 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Dry Hair","Curly Hair","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Nourishing Argan Elixir - 100 ml' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Styling Collection","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Session Spray Medium - 300 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Session Spray Strong - 300 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Signature Brush' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Care Collection","Silver & Blonde","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Silver Mask - 190 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Care Collection","Silver & Blonde","New"]' WHERE "brand" = 'eloure' AND "name" = 'Silver Shampoo - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Styling Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'Soft Gloss Mist - 200 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Bestsellers","New"]' WHERE "brand" = 'eloure' AND "name" = 'Styling Gel Strong - 150 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Fine Hair","New"]' WHERE "brand" = 'eloure' AND "name" = 'Texturizing Salt Mist - 200 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Fine Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Texturizing Volume Spray (Travel Size) - 75 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Bestsellers"]' WHERE "brand" = 'eloure' AND "name" = 'Texturizing Volume Spray - 200 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Treatments & Sets","Care Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'The Radiant Care Collection' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Treatments & Sets","Styling Collection","New"]' WHERE "brand" = 'eloure' AND "name" = 'The Volume & Glow Collection' AND "category" = 'Treatments & Sets';
UPDATE "Product" SET "category" = '["Care Collection","Fine Hair","Bestsellers","New"]' WHERE "brand" = 'eloure' AND "name" = 'Volumizing Conditioner - 250 ml' AND "category" = 'Care Collection';
UPDATE "Product" SET "category" = '["Styling Collection","Fine Hair"]' WHERE "brand" = 'eloure' AND "name" = 'Volumizing Mousse Strong - 300 ml' AND "category" = 'Styling Collection';
UPDATE "Product" SET "category" = '["Care Collection","Fine Hair","Bestsellers","New"]' WHERE "brand" = 'eloure' AND "name" = 'Volumizing Shampoo - 250 ml' AND "category" = 'Care Collection';
